"""initial migration

Revision ID: e46c46390dc8
Revises: 
Create Date: 2023-02-05 14:59:00.741781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46c46390dc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_authors'))
    )
    op.create_index(op.f('ix_blog_authors_name'), 'blog_authors', ['name'], unique=False)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries'))
    )
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=True)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages'))
    )
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=True)
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturers'))
    )
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=True)
    op.create_table('blog_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_blog_users_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_users'))
    )
    op.create_index(op.f('ix_blog_users_customer_id'), 'blog_users', ['customer_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_timestamp'), 'orders', ['timestamp'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cpu', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], name=op.f('fk_products_manufacturer_id_manufacturers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_manufacturer_id'), 'products', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_index(op.f('ix_products_year'), 'products', ['year'], unique=False)
    op.create_table('blog_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('translation_of_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['blog_authors.id'], name=op.f('fk_blog_articles_author_id_blog_authors')),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_blog_articles_language_id_languages')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_blog_articles_product_id_products')),
    sa.ForeignKeyConstraint(['translation_of_id'], ['blog_articles.id'], name=op.f('fk_blog_articles_translation_of_id_blog_articles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_articles'))
    )
    op.create_index(op.f('ix_blog_articles_author_id'), 'blog_articles', ['author_id'], unique=False)
    op.create_index(op.f('ix_blog_articles_language_id'), 'blog_articles', ['language_id'], unique=False)
    op.create_index(op.f('ix_blog_articles_product_id'), 'blog_articles', ['product_id'], unique=False)
    op.create_index(op.f('ix_blog_articles_timestamp'), 'blog_articles', ['timestamp'], unique=False)
    op.create_index(op.f('ix_blog_articles_title'), 'blog_articles', ['title'], unique=False)
    op.create_index(op.f('ix_blog_articles_translation_of_id'), 'blog_articles', ['translation_of_id'], unique=False)
    op.create_table('blog_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['blog_users.id'], name=op.f('fk_blog_sessions_user_id_blog_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_sessions'))
    )
    op.create_index(op.f('ix_blog_sessions_user_id'), 'blog_sessions', ['user_id'], unique=False)
    op.create_table('orders_items',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_orders_items_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orders_items_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'order_id', name=op.f('pk_orders_items'))
    )
    op.create_table('product_reviews',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_product_reviews_customer_id_customers')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_reviews_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'customer_id', name=op.f('pk_product_reviews'))
    )
    op.create_index(op.f('ix_product_reviews_timestamp'), 'product_reviews', ['timestamp'], unique=False)
    op.create_table('products_countries',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_products_countries_country_id_countries')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_products_countries_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'country_id', name=op.f('pk_products_countries'))
    )
    op.create_table('blog_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['blog_articles.id'], name=op.f('fk_blog_views_article_id_blog_articles')),
    sa.ForeignKeyConstraint(['session_id'], ['blog_sessions.id'], name=op.f('fk_blog_views_session_id_blog_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_views'))
    )
    op.create_index(op.f('ix_blog_views_timestamp'), 'blog_views', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_views_timestamp'), table_name='blog_views')
    op.drop_table('blog_views')
    op.drop_table('products_countries')
    op.drop_index(op.f('ix_product_reviews_timestamp'), table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_table('orders_items')
    op.drop_index(op.f('ix_blog_sessions_user_id'), table_name='blog_sessions')
    op.drop_table('blog_sessions')
    op.drop_index(op.f('ix_blog_articles_translation_of_id'), table_name='blog_articles')
    op.drop_index(op.f('ix_blog_articles_title'), table_name='blog_articles')
    op.drop_index(op.f('ix_blog_articles_timestamp'), table_name='blog_articles')
    op.drop_index(op.f('ix_blog_articles_product_id'), table_name='blog_articles')
    op.drop_index(op.f('ix_blog_articles_language_id'), table_name='blog_articles')
    op.drop_index(op.f('ix_blog_articles_author_id'), table_name='blog_articles')
    op.drop_table('blog_articles')
    op.drop_index(op.f('ix_products_year'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_manufacturer_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_timestamp'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_blog_users_customer_id'), table_name='blog_users')
    op.drop_table('blog_users')
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_blog_authors_name'), table_name='blog_authors')
    op.drop_table('blog_authors')
    # ### end Alembic commands ###
