"""blog integration

Revision ID: b8c2435dfe77
Revises: 251207424ac9
Create Date: 2023-01-29 17:57:04.954041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c2435dfe77'
down_revision = '251207424ac9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_authors'))
    )
    with op.batch_alter_table('blog_authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_authors_name'), ['name'], unique=False)

    op.create_table('blog_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_blog_users_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_users'))
    )
    with op.batch_alter_table('blog_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_users_customer_id'), ['customer_id'], unique=False)

    op.create_table('blog_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['blog_authors.id'], name=op.f('fk_blog_articles_author_id_blog_authors')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_blog_articles_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_articles'))
    )
    with op.batch_alter_table('blog_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_articles_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_articles_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_articles_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_articles_title'), ['title'], unique=False)

    op.create_table('blog_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['blog_users.id'], name=op.f('fk_blog_sessions_user_id_blog_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_sessions'))
    )
    with op.batch_alter_table('blog_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('blog_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['blog_articles.id'], name=op.f('fk_blog_views_article_id_blog_articles')),
    sa.ForeignKeyConstraint(['session_id'], ['blog_sessions.id'], name=op.f('fk_blog_views_session_id_blog_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_views'))
    )
    with op.batch_alter_table('blog_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_views_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_views_timestamp'))

    op.drop_table('blog_views')
    with op.batch_alter_table('blog_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_sessions_user_id'))

    op.drop_table('blog_sessions')
    with op.batch_alter_table('blog_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_articles_title'))
        batch_op.drop_index(batch_op.f('ix_blog_articles_timestamp'))
        batch_op.drop_index(batch_op.f('ix_blog_articles_product_id'))
        batch_op.drop_index(batch_op.f('ix_blog_articles_author_id'))

    op.drop_table('blog_articles')
    with op.batch_alter_table('blog_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_users_customer_id'))

    op.drop_table('blog_users')
    with op.batch_alter_table('blog_authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_authors_name'))

    op.drop_table('blog_authors')
    # ### end Alembic commands ###
