"""multi-language support

Revision ID: bdca026c3911
Revises: b8c2435dfe77
Create Date: 2023-01-29 18:38:29.466369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdca026c3911'
down_revision = 'b8c2435dfe77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages'))
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_name'), ['name'], unique=True)

    with op.batch_alter_table('blog_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('translation_of_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_blog_articles_language_id'), ['language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_articles_translation_of_id'), ['translation_of_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_blog_articles_translation_of_id_blog_articles'), 'blog_articles', ['translation_of_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_blog_articles_language_id_languages'), 'languages', ['language_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_articles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_blog_articles_language_id_languages'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_blog_articles_translation_of_id_blog_articles'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_blog_articles_translation_of_id'))
        batch_op.drop_index(batch_op.f('ix_blog_articles_language_id'))
        batch_op.drop_column('translation_of_id')
        batch_op.drop_column('language_id')

    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_name'))

    op.drop_table('languages')
    # ### end Alembic commands ###
